language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - mmuratakbiyik@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: jvj90CLujZK2siAuer0oK6moovrgbTqZbG/14FT5JeP/DX26W7Re9OsR56f+r5maEJYES6m8NxXIiDzrpih6drHrIw6B9K4a5RLs17HtRh2O6O9PzceWJyOXSQzVcO0vCJzwxMtq8KlWlCGKbvEEjM7xZ70xD0rHyITQZIr2D1JFf6StHvOBMp6SdIhlZpEJ+plmKk5WJEAUVCxLS5uZZRWwc3Ow1+M6ZDidMTXx0vpl/gFqgY63E1XWhXp853LHxXh2IEVGZmJvL9ORHCKiLZ22cnLmAL6ne2OG8bW+pVkj/zE1zIOg+30A/DWo1h5eoICg8LBtJ6PeaOznkxkQ1YZwhmAOl+fUUIwbvmlEpsuo807TUrIUb0mdycz7A+g07O/c9dSKbJmA0l1vsNOl59EFdFqbCikkVnxALdVKwKThSxDm1tWT1EJignsw4ty4DDyawxp+IyfzPr49mfLXpca/kDB8o8rbBzm/4LSwpRqNi6YgCBBClvxWwmMx4Lv/6PAPVTv8ATWiNq9zG4Obgd/IVxoq+WAA7w8KTRA55OPCIY6zW1ukjzoU//EEvW6Zg8M30ypmw3oHbKJNYCOY4A9FabwKz11yssd8TzdYm+91iAGgqr4x/0Pq1e5arw4HhAi3MTSmvtUalFbrxdH6Y18a3LFBqwZhnrGIOw4z2mk=
  - secure: pubjENLrxvbaq0fUhq8Jqm9mRLOC0WvveCKB5DwZ5H0uPMYnPLF0Z4T/ka4bHkqUw0xKBuq94Fn8ILAkGr09gIoi4Lx3bDHQ7ieo+56eEL8pBLTuRWDokvJLgVx20x28Dqa7ufdYDWVPoWw1Z1ZWaEszwSOUfaUmj7Eh2jRAYVrP7vnKPLqyJYn39GLIqJ/e/T9IumwfZPlHaWy1AbexxsBg0Md/294OJ/unN8xDpMgfVKPI5QXRT3EJSSH4l9ODOQjNwFfecjYCep8b095fzIjLrdRA1LviZUBcCNcUZ7zM/iDVhGNFs3s08rs2F+O8peGsmqrgTfmRaVq5ansBCckXKy8w/IHFffNj1KzY3JyI16vjaKReuLgJI5uVyjWruYdKALz+WBKn5c+Vo4WCCTDXVwzdVK9wLgI9uN+VKJ7D7Yh0ufazfkEk4FAIC9H8Zim/42bD0w2sy3ZmZAhG4Zr4QoYpnQ2apcTJlW7wA+g/U1ahemOmzQH1tsPnoCU7o6Zauw44vRrrKSCBSW3CrfcNw39mQ5ejcNXtgCgeQDAH4Qtbv/FwLIUWaGoFHGBwjxrPHRE7hcU5C4EDx5qI/GLK2QRnwi0yoYgAvBzDM/8UNoe0Ei/KIFJz9zrjzhZ/i/xyb2fUYcsrYjcp1no0Nu0hU8M+s26VW8i0wt145I8=
  - secure: LDhK/Ef/EmzUb6Lt5SN3R1DJXFiSyQnnWjdqZmeBfLOOA74V0NXDt4xdJWuPzQ1RuRrBXk1YR0soYs98z6zZVl9AVJHacz/wcdUt91qn8fTvRq91QnQvw+z29nC1mrn0sTPsf0GwGi+oRuVveDt4iGhskSwxyRDyYfZK0el3CI1C0qeh8JU3aaFW980DAK6HTkTxL2gsq5esn5o+kqlMvPnqe1ULpV7As0btigsTCj+9tZBIgMKITfAJ2Lp/q2A9cH/2GrixBZu85JMR5COQAFZR7NHWDXjjbDcj+jusCZ35KPbeciovZmHwlrTeKRfbIWYlmhKi7zCq/Rw2zfkK4HBe+aIWjgWaF1p8hyxCVmQin4d7Pp7cymceGq9sHw0el3rykE9EMeaqc8jTv3vLr55XuVMxvVxwBHBpU7x8KSv/U2aYC61zy2qVlBm6BY0RKGbsoSDNSvEKtcEvdPLTw28XBXBIvMUPnU7FqZ/br+O0+y460l4446okIuAx2xhNDPMfQwHry5DK5G2l0G2AiEnoV5ztW3SrLBnLjiM3Vq+4cmGycrs/KVHS2DFfeObMRxfZUpjRpA/UVxIgUiXEiIwW7Uy6Ym+Qq5nmN4rEsp5DEreyIi56oBDLhL4XdzukwKbmJOqdzrPTHPgbtIgT+VzXJ7Kcp0CFlU3X8+udC4c=
  - secure: IHejNGILoojeo6su+lzqIjosDSbiFFycuWT/jexYRHtbAJTpDO4fjKxhS3FTJYDMTGvRG8OjCjzDVqvq3kzvAGNTGMrlK+U2H7OQlK+OwmNlfEMqvwqNt34dJPzj8I8vIGuOUxdVT3ZAV8DkO65taWoTAdVTvIp2t8WbkgEeAe4qAmoJ+u0YSrXLNpJ/gUFsr6V7LV1GOv41XUpEOjjeoGw389nO+mosdpl6GI7pFCJ00CInH/B1xGWM20yY9opraQX6tLJnEczLxjJdhNBhkt+liChv2GT7H3KmFTC41ncRiB7PfzGbDCOtdAdz85PJHUVXGsco00L6osv5d7Y1S9wnAAvztwO/IwS8XT2RCw9biTUvfjnjajogdbMnD+ZcfgnPo5B2QHbuEV+roaOWyUb564sjQuMZEV/6+n/sozUyDmr281eiKPGyafcxvdcHkcIyUMS44syk97XkFOfhOvh6HBhN5e5AnSYJvNP/4zA+r0EwCs5Vnqv5QeUn9TBxZ1mc5Jx79NY9pCIaVCNLyDKZO8v0wnVMOiWwOouu0GexA6YEJKkRXn1Vnxf/ziyYNVcOG7CaL+3IxdBNC9ca6Gfonu58EVD1iQqblzDnbrJsZdP9Fo2nVRP2qp3pWgbylSR/vuJaoIva+h9gGP1t7588h4h6n+TKATYsm2wi5vo=
  - secure: lvvLc/GaaDbQatL95QdH9W1BvHgG6cNtTJNAMh73s0J5L7hpRHWdD/bRPAGkyZTCPvnim51UoedsSjRr3fdfgvkw0tMvFr2/Dh/LQBNraOrlLosg5SewBESP8TMofdc2BjQy3XvUH0uHBlKp3vlXM4dSNbzSX24Ufvdr6tnaDVFuVz0pcvmjm4490XjCB8Fvv7OZFyZUXHsVOC2wo90p+oJZLM7s1bH0ARZaGceZb1KV3VZH/aDIWN6iLAZ1yE7kVpS14bgVCS4hZlhtJt5Av+z2TxXLeel9Ktb9hQi9a/Ev87Isde0m0YoW5I/DTBaUUdPbmkD8VdrwDe/dlUWM88qZ6ZQR4lcyByKk8cDSNw1XZbuPZ7ZcstDLbuy4G5U3etM3+DjzmKWKt83y00DCN3pTAP94AUI5Ivzw5BJGIPBkllr5MbqNsZsMokuq/0GBG0SKe/beAmHT+b4X66msr2GOtXSZP1BInA9S2kf4ptpw4fNE1tRtoGoljURnR3TYXm9vsLGkbHTw0OYTYJS7kCYAEdeA9u2BJXvK4rHpZn8SA5v9UUIT+dF0FY323gTEJElvVvC2nzEx6gGxrWTuaj6MgcGTcRttz53sYxnWESEJhV4u87I3UtDcF+io0piK+lXLQfeSZJqMDtFhkUuxGZb/rNYHuETbwaVqtkphAbY=
before_install:
- chmod +x mvnw
- gem install travis -v 1.8.5
- sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=service-disvovery-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=52.53.169.60
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_amazon_ecs.sh
